import { Shoe, AppNotification, UserProfile } from "@/types";

export const MOCK_SHOES: Shoe[] = [
  {
    id: "shoe-1",
    name: "Air Jordan 1 Retro High OG",
    slug: "air-jordan-1-retro-high-og",
    brand: "Jordan",
    category: "basketball",
    gender: "men",
    price: 180,
    originalPrice: 210,
    images: [
      "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "The legend lives on in the Air Jordan 1 Retro High OG. Staying true to the silhouette that kicked off the Jumpman legacy in 1985, this version delivers vintage vibes with premium leather construction and signature encapsulated Air-Sole cushioning.",
    details: {
      cushioning: "Encapsulated Air-Sole unit in heel",
      upper: "Premium full-grain leather & nubuck",
      sole: "Solid rubber outsole with deep flex grooves",
      sku: "DZ5485-612",
      releaseYear: 2023,
    },
    colors: [
      { name: "Chicago Red / White", hex: "#dc2626" },
      { name: "Royal Blue / Black", hex: "#2563eb" },
      { name: "Shadow Grey", hex: "#52525b" },
    ],
    sizes: [7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    inStock: true,
    stockCount: 14,
    isNew: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 342,
    reviews: [
      {
        id: "rev-1",
        userName: "Marcus K.",
        rating: 5,
        date: "2024-03-12",
        title: "All-time grail sneaker",
        comment: "Materials are insane! Leather feels soft right out of the box and the colorway matches everything.",
        verified: true,
      },
      {
        id: "rev-2",
        userName: "Elena R.",
        rating: 5,
        date: "2024-02-28",
        title: "Great ankle support and timeless style",
        comment: "Fits true to size. Delivery was fast and shoes came in mint condition box.",
        verified: true,
      },
    ],
  },
  {
    id: "shoe-2",
    name: "Nike Dunk Low Retro",
    slug: "nike-dunk-low-retro-panda",
    brand: "Nike",
    category: "lifestyle",
    gender: "unisex",
    price: 115,
    images: [
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1512374382149-233c42b6613c?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "Created for the hardwood but taken to the streets, the '80s icon returns with classic details and throwback hoops flair. Channeling vintage vibes back onto the street, its padded, low-cut collar lets you comfortably take your game anywhere.",
    details: {
      cushioning: "Lightweight foam midsole",
      upper: "Crisp leather with slight sheen",
      sole: "Durable rubber outsole with classic hoops pivot circle",
      sku: "DD1391-100",
      releaseYear: 2023,
    },
    colors: [
      { name: "Panda Black / White", hex: "#09090b" },
      { name: "Coast Blue", hex: "#38bdf8" },
      { name: "Grey Fog", hex: "#a1a1aa" },
    ],
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    inStock: true,
    stockCount: 29,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 512,
  },
  {
    id: "shoe-3",
    name: "Adidas Ultraboost Light",
    slug: "adidas-ultraboost-light",
    brand: "Adidas",
    category: "running",
    gender: "men",
    price: 190,
    originalPrice: 220,
    images: [
      "https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever. The magic lies in the Light BOOST midsole, a new generation of adidas BOOST. Its unique molecule design achieves the lightest BOOST foam to date.",
    details: {
      cushioning: "Light BOOST 30% lighter foam",
      upper: "PRIMEKNIT+ textile yarn upper",
      sole: "Continental Better Rubber outsole",
      sku: "HQ6351",
      releaseYear: 2024,
    },
    colors: [
      { name: "Core Black", hex: "#18181b" },
      { name: "Solar Red", hex: "#ef4444" },
      { name: "Cloud White", hex: "#fafafa" },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    inStock: true,
    stockCount: 18,
    isNew: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 189,
  },
  {
    id: "shoe-4",
    name: "New Balance 990v6 Made in USA",
    slug: "new-balance-990v6-castlerock",
    brand: "New Balance",
    category: "lifestyle",
    gender: "unisex",
    price: 200,
    images: [
      "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "The designers of the first 990 were tasked with creating the single best running shoe on the market. The 990v6 embraces this mandate with a series of performance-inspired updates including FuelCell midsole cushioning.",
    details: {
      cushioning: "FuelCell foam delivers a propulsive feel",
      upper: "Pigskin and mesh upper",
      sole: "ENCAP midsole cushioning combines lightweight foam with durable polyurethane rim",
      sku: "M990GL6",
      releaseYear: 2023,
    },
    colors: [
      { name: "Castlerock Grey", hex: "#71717a" },
      { name: "Triple Black", hex: "#18181b" },
      { name: "Navy Blue", hex: "#1e3a8a" },
    ],
    sizes: [7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12, 13],
    inStock: true,
    stockCount: 11,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 220,
  },
  {
    id: "shoe-5",
    name: "Air Jordan 4 Retro SE Craft",
    slug: "air-jordan-4-retro-se-craft",
    brand: "Jordan",
    category: "basketball",
    gender: "men",
    price: 215,
    originalPrice: 240,
    images: [
      "https://images.unsplash.com/photo-1579338559194-a162d19bf842?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1597045566677-8cf032ed6634?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "The Air Jordan 4 Retro delivers lightweight cushioning with sculpted midsole and mesh inserts. An iconic piece of sneaker history featuring tactile suedes, premium cracked leather, and distinct molded eyelets.",
    details: {
      cushioning: "Visible Air unit in heel & encapsulated forefoot Air",
      upper: "Mixed suede, textile, and grid mesh",
      sole: "Herringbone pattern rubber outsole",
      sku: "DV3742-021",
      releaseYear: 2024,
    },
    colors: [
      { name: "Photon Dust / Grey", hex: "#d4d4d8" },
      { name: "Military Black", hex: "#27272a" },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    inStock: true,
    stockCount: 7,
    isNew: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 418,
  },
  {
    id: "shoe-6",
    name: "Adidas Samba OG",
    slug: "adidas-samba-og-white",
    brand: "Adidas",
    category: "lifestyle",
    gender: "unisex",
    price: 100,
    images: [
      "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "Born on the pitch, the Samba is a timeless icon of street style. This version stays true to its legacy with a tasteful, low-profile leather upper, suede overlays and gum sole.",
    details: {
      cushioning: "Lightweight die-cut EVA sockliner",
      upper: "Full grain leather upper with gritty suede T-toe",
      sole: "Soft gum rubber cupsole",
      sku: "B75806",
      releaseYear: 2023,
    },
    colors: [
      { name: "Cloud White / Core Black", hex: "#f4f4f5" },
      { name: "Core Black / Cloud White", hex: "#18181b" },
    ],
    sizes: [6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11],
    inStock: true,
    stockCount: 35,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 654,
  },
  {
    id: "shoe-7",
    name: "Nike Air Max 90 Futura",
    slug: "nike-air-max-90-futura",
    brand: "Nike",
    category: "running",
    gender: "women",
    price: 150,
    originalPrice: 170,
    images: [
      "https://images.unsplash.com/photo-1605348532760-6753d2c43329?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "The Nike Air Max 90 Futura reinvents the icon of Air through your eyes—from design to testing to styling. Sawtooth edging around the toe and partially floating Swoosh deliver skillfully crafted luxury.",
    details: {
      cushioning: "Max Air cushioning originally designed for performance running",
      upper: "Textile with stitched synthetic overlays",
      sole: "Rubber Waffle outsole delivers heritage traction",
      sku: "DM9922-101",
      releaseYear: 2024,
    },
    colors: [
      { name: "Pale Ivory / Pink", hex: "#fbcfe8" },
      { name: "Summit White", hex: "#f5f5f5" },
    ],
    sizes: [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5],
    inStock: true,
    stockCount: 16,
    isNew: true,
    rating: 4.8,
    reviewCount: 97,
  },
  {
    id: "shoe-8",
    name: "Puma MB.03 'Toxic'",
    slug: "puma-mb03-toxic",
    brand: "Puma",
    category: "basketball",
    gender: "men",
    price: 125,
    originalPrice: 145,
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "LaMelo Ball is 1-of-1. And his third signature sneaker, MB.03, takes a journey to the alternate universe that is the Melo world. Highlighted by slime artwork and space-age neon accents.",
    details: {
      cushioning: "NITRO foam-infused midsole for explosive responsiveness",
      upper: "Engineered woven mesh with seamless scratch cutouts",
      sole: "Non-slip rubber compound for high-traction multidirectional cuts",
      sku: "378916-01",
      releaseYear: 2024,
    },
    colors: [
      { name: "Toxic Neon Pink / Purple", hex: "#a855f7" },
      { name: "Alien Green", hex: "#84cc16" },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    inStock: true,
    stockCount: 8,
    isNew: true,
    rating: 4.7,
    reviewCount: 144,
  },
  {
    id: "shoe-9",
    name: "New Balance 550 Retro Basketball",
    slug: "new-balance-550-white-green",
    brand: "New Balance",
    category: "lifestyle",
    gender: "unisex",
    price: 110,
    images: [
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "The 550 debuted in 1989 and made its mark on basketball courts from coast to coast. After its initial run, the 550 was filed away in the archives, before being reintroduced in limited-edition releases. The low-top, streamlined silhouette is a clean take on the heavy-duty designs of the late '80s.",
    details: {
      cushioning: "EVA foam wedge in midsole",
      upper: "Premium leather and perforated quarter panels",
      sole: "Non-marking rubber cupsole",
      sku: "BB550WT1",
      releaseYear: 2023,
    },
    colors: [
      { name: "White / Pine Green", hex: "#15803d" },
      { name: "White / Navy", hex: "#1d4ed8" },
      { name: "White / Red", hex: "#b91c1c" },
    ],
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    inStock: true,
    stockCount: 22,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 382,
  },
  {
    id: "shoe-10",
    name: "Nike SB Dunk Low Pro 'Wheat'",
    slug: "nike-sb-dunk-low-pro-wheat",
    brand: "Nike",
    category: "skateboarding",
    gender: "men",
    price: 120,
    originalPrice: 140,
    images: [
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1579338559194-a162d19bf842?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "The Nike SB Dunk Low Pro delivers iconic Dunk style in a low-cut silhouette. A Zoom Air unit in the heel and a padded tongue provide the comfort you need when skateboarding.",
    details: {
      cushioning: "Zoom Air unit in the sockliner for responsive cushioning",
      upper: "Rich buttery pigskin suede",
      sole: "Circular tread with forefoot pivot circle gives multidirectional grip",
      sku: "BQ6817-204",
      releaseYear: 2023,
    },
    colors: [
      { name: "Wheat Mocha", hex: "#b45309" },
      { name: "Classic Navy", hex: "#1e3a8a" },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5],
    inStock: true,
    stockCount: 15,
    rating: 4.8,
    reviewCount: 175,
  },
  {
    id: "shoe-11",
    name: "Nike ZoomX Vaporfly NEXT% 3",
    slug: "nike-zoomx-vaporfly-next-3",
    brand: "Nike",
    category: "running",
    gender: "unisex",
    price: 260,
    images: [
      "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "Catch 'em if you can. Giving you race-day speed to conquer any distance, the Nike Vaporfly 3 is made for the chasers, the racers and the elevated pacers who can't turn down the thrill of the pursuit.",
    details: {
      cushioning: "Full-length carbon fiber Flyplate with resilient ZoomX foam",
      upper: "Specifically selected Flyknit yarns with zones of engineered support",
      sole: "Thin waffle outsole rubber to reduce weight while preserving grip",
      sku: "DV4129-100",
      releaseYear: 2024,
    },
    colors: [
      { name: "Hyper Pink / Laser Orange", hex: "#f43f5e" },
      { name: "Pure Platinum", hex: "#e4e4e7" },
    ],
    sizes: [7, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    inStock: true,
    stockCount: 9,
    isNew: true,
    rating: 5.0,
    reviewCount: 88,
  },
  {
    id: "shoe-12",
    name: "Jordan 1 Low Travis Scott Reverse Mocha",
    slug: "jordan-1-low-travis-scott-reverse-mocha",
    brand: "Jordan",
    category: "lifestyle",
    gender: "unisex",
    price: 350,
    originalPrice: 420,
    images: [
      "https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1000&q=80",
    ],
    description:
      "A tribute to the iconic collaboration between hip-hop superstar Travis Scott and the Jordan Brand. Featuring backward oversized Swoosh branding, Cactus Jack embroidery on heel tab, and premium nubuck leather.",
    details: {
      cushioning: "Air-Sole unit in heel",
      upper: "Mocha durabuck with sail leather overlays",
      sole: "Vintage sail rubber midsole with mocha outsole",
      sku: "DM7866-162",
      releaseYear: 2023,
    },
    colors: [
      { name: "Sail / Reverse Mocha", hex: "#78350f" },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    inStock: true,
    stockCount: 3,
    isFeatured: true,
    rating: 5.0,
    reviewCount: 684,
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif-1",
    title: "Order #SNK-9281 Dispatched! 📦",
    message: "Your Air Jordan 1 Retro High OG is on its way. Track live delivery status in your orders.",
    type: "order",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(), // 35 min ago
    link: "/profile",
  },
  {
    id: "notif-2",
    title: "🔥 Flash Drop Alert!",
    message: "Exclusive Travis Scott x Jordan 1 Low restocked in limited sizes. Don't sleep on this drop!",
    type: "drop",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(), // 4h ago
    link: "/shoes/jordan-1-low-travis-scott-reverse-mocha",
  },
  {
    id: "notif-3",
    title: "Weekend VIP Promo: 15% OFF",
    message: "Use promo code 'SNEAKER15' at checkout to get an instant 15% discount on all lifestyle kicks.",
    type: "promo",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
    link: "/shoes",
  },
  {
    id: "notif-4",
    title: "Welcome to SNEAKERS! 👟",
    message: "Welcome to the home of authentic hype and performance kicks. Enjoy free shipping on orders over $150.",
    type: "system",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(), // 3 days ago
    link: "/",
  },
];

export const MOCK_USER: UserProfile = {
  id: "demo-user-123",
  email: "alex.sneakerhead@example.com",
  fullName: "Alex Rivera",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
  phone: "+1 (555) 019-2834",
  address: {
    fullName: "Alex Rivera",
    email: "alex.sneakerhead@example.com",
    phone: "+1 (555) 019-2834",
    street: "742 Evergreen Terrace, Apt 4B",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90001",
    country: "United States",
  },
  createdAt: "2024-01-15T10:00:00.000Z",
};

export const PROMO_CODES: Record<string, { discountPercent: number; description: string }> = {
  SNEAKER15: { discountPercent: 15, description: "15% off entire order" },
  KICKS10: { discountPercent: 10, description: "10% off entire order" },
  FREESHIP: { discountPercent: 0, description: "Free shipping upgrade" },
};
